baseURL = "https://nanet.si/"
languageCode = "en-us"
defaultContentLanguage = 'slo'
title = "nanet.si"
disableKinds = ["taxonomy", "term"]
googleAnalytics = "UA-179552918-1"

[languages.en]
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 1

[languages.slo]
contentDir = 'content/slo'
languageCode = 'slo'
languageName = 'Slovenian'
weight = 0
